version: '3.8'

services:
  api:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_URL=postgres://root:password@local_pgdb:5432/postgres?sslmode=disable
    networks:
      - postgresql_default
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 512M

networks:
  postgresql_default:
    external: true
